title: Ryan Kennedy
description: Analysts & Developer 
author:
  name: Ryan Kennedy
  email: 'sirryankennedy@gmail.com'
metadata:
    description: 'Personal website and resume of Ryan Kennedy, analyst and consultant.'

website: "ryankennedy.me"
facebook: m.me/sirryankennedy
linkedin: https://www.linkedin.com/in/sirryankennedy/
instagram: https://www.instagram.com/sirryankennedy/
upwork: https://www.upwork.com/freelancers/~017d94a65b8984aabd